services:
  - type: web
    name: earning-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_IDS
        value: "7013309955"